version: '3.3'

services:
  tomcat:
    build:
      context: .
      dockerfile: Tomcat.Dockerfile
    image: myContainer
    container_name: myContainer
    ports:
      - 8080:8080
#    logging:
#      driver: splunk
#      options:
#        splunk-url: https://172.20.0.4:8088
#        splunk-token: ""
#        splunk-insecureskipverify: 'true'
    networks:
      - cluster

  splunk:
    environment:
      - "SPLUNK_START_ARGS=--accept-license --no-prompt --answer-yes"
      - "SPLUNK_USERNAME=chuongdn79"
      - "SPLUNK_PASSWORD=chuong123"
    hostname: splunk
    image: splunk/splunk:latest
    container_name: udacity-splunk
    ports:
      - 8000:8000
      - 8088:8088
    restart: always
    networks:
      - cluster

  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    image: myJenkins
    container_name: myJenkins
    restart: on-failure
    environment:
      JENKINS_USER: chuong123
      JENKINS_PASSWORD: chuong
      TOMCAT_USER: chuong
      TOMCAT_PASSWORD: chuong123
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:8080
    networks:
      - cluster

networks:
  cluster:
    driver: bridge