jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_USER}
          password: ${JENKINS_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:ecommerce"
        - "Overall/Read:anonymous"
        - "Job/Read:anonymous"
        - "View/Read:anonymous"
#      remotingSecurity:
#        enabled: true
#    security:
#      queueItemAuthenticator:
#        authenticators:
#          - global:
#              strategy: triggeringUsersAuthorizationStrategy
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "tomcat"
              username: ${TOMCAT_USER}
              password: ${TOMCAT_PASSWORD}
              description: "Tomcat credentials for deployment."
              scope: GLOBAL
unclassified:
  location:
    url: http://127.0.0.1:8080

jobs:
  - script: >
      pipelineJob('e-Commerce') {
          description("e-Commerce")
          properties{
              githubProjectUrl ('')
          }
          triggers {
              githubPush()
          }
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url('')
                          }
                          branch('main')
                      }
                  }
                  scriptPath('Jenkinsfile')
              }
          }
      }
